### ISSUE TITLE
An error occurred while deleting the cache. ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by gnowland** [CagriAldemir/react-cache-buster#1]
Hi @CagriAldemir, I'm receiving the following error on app load, causing a blank white screen:

```text
An error occurred while deleting the cache. 
    at CacheBuster (http://localhost:3000/static/js/vendors~main.chunk.js:125888:28)
    at App
    at UserSessionProvider (http://localhost:3000/static/js/main.chunk.js:3950:3)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4049
log @ index.modern.js:80
(anonymous) @ index.modern.js:166
_catch @ index.modern.js:53
refreshCacheAndReload @ index.modern.js:149
CacheBuster @ index.modern.js:182
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index.modern.js:97
Promise.then (async)
(anonymous) @ index.modern.js:91
Promise.then (async)
(anonymous) @ index.modern.js:90
_catch @ index.modern.js:51
checkCacheStatus @ index.modern.js:89
(anonymous) @ index.modern.js:84
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157

ReferenceError: caches is not defined
    at index.modern.js:151
    at index.modern.js:162
    at _catch (index.modern.js:51)
    at refreshCacheAndReload (index.modern.js:149)
    at CacheBuster (index.modern.js:182)
    at renderWithHooks (react-dom.development.js:14985)
    at updateFunctionComponent (react-dom.development.js:17356)
    at beginWork (react-dom.development.js:19063)
    at beginWork$1 (react-dom.development.js:23940)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at scheduleUpdateOnFiber (react-dom.development.js:21893)
    at dispatchAction (react-dom.development.js:16139)
    at index.modern.js:97 '\n    at CacheBuster (http://localhost:3000/static/js/vendors~main.chunk.js:125888:28)\n    at App\n    at UserSessionProvider (http://localhost:3000/static/js/main.chunk.js:3950:3)'
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4049
log @ index.modern.js:80
(anonymous) @ index.modern.js:167
_catch @ index.modern.js:53
refreshCacheAndReload @ index.modern.js:149
CacheBuster @ index.modern.js:182
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index.modern.js:97
Promise.then (async)
(anonymous) @ index.modern.js:91
Promise.then (async)
(anonymous) @ index.modern.js:90
_catch @ index.modern.js:51
checkCacheStatus @ index.modern.js:89
(anonymous) @ index.modern.js:84
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```

The error appears on [src/CacheBuster.js#L77](https://github.com/CagriAldemir/react-cache-buster/blob/f2dcc5d11a059c0f6cabd86725e549b09900f2fb/src/CacheBuster.js#L77)

I'm using Brave Browser Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64) on an Apple MacBook Pro running MacOS Catalina v10.15.7

Your assistance is greatly appreciated!

**Comment by gnowland** [comment]
Temporarily fixed by making the `isEnabled` prop contingent on `window.caches`:

```js
<CacheBuster
    isEnabled={window.caches === undefined ? false : true}
>
```
...but would love to find a more permanent solution to the underlying issue :).

**Comment by CagriAldemir** [comment]
Hi @gnowland 
I deployed a new version of React Cache Buster. I expect the issue to be resolved with this version. You can upgrade your react-cache-buster version to 0.1.5 in package.json

Thanks for the comment !
